-- MySQL Script generated by MySQL Workbench
-- Thu Jul  2 10:18:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`document_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`document_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `deleted_at` DATETIME NULL,
  `created_at` DATETIME NULL,
  `update_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lawyers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lawyers` (
  `id` INT NOT NULL,
  `names` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `document_type_id` INT NOT NULL,
  `document_number` INT NOT NULL,
  `start_date` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  `created_at` DATETIME NULL,
  `update_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_document_types_idx` (`document_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_document_types`
    FOREIGN KEY (`document_type_id`)
    REFERENCES `mydb`.`document_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `names` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `document_type_id` INT NOT NULL,
  `document_number` INT NULL,
  `deleted_at` DATETIME NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`statuses` (
  `id` INT NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `deleted_at` VARCHAR(45) NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cases` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `client_id` INT NOT NULL,
  `cost` DECIMAL(10,4) NOT NULL,
  `status_id` INT NOT NULL,
  `deleted_at` DATETIME NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clients_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_statuses_idx` (`status_id` ASC) VISIBLE,
  CONSTRAINT `fk_clients`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_statuses`
    FOREIGN KEY (`status_id`)
    REFERENCES `mydb`.`statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cases_lawyers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cases_lawyers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `case_id` INT NOT NULL,
  `lawyer_id` INT NULL,
  `deleted_at` DATETIME NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lawyers_idx` (`lawyer_id` ASC) VISIBLE,
  INDEX `fk_cases_idx` (`case_id` ASC) VISIBLE,
  CONSTRAINT `fk_lawyers`
    FOREIGN KEY (`lawyer_id`)
    REFERENCES `mydb`.`lawyers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cases`
    FOREIGN KEY (`case_id`)
    REFERENCES `mydb`.`cases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
